### ISSUE TITLE
index being added to end of geohash string

### ISSUE THREAD

**Issue by erikarasnick** [degauss-org/h3#2]
https://github.com/degauss-org/h3/blob/09a1e2a8943c5f18c30c29a6e7cee2994870129a/entrypoint.R#L32-L33

assigning the safe harbor geohash as the names, then unlisting, is adding an "index" to the end of any duplicated geohashes.

My workaround was to use a tibble, but that may not be the best for this application. 

```
h3_sh <- readRDS("us_h3_3_population_20k_minimum_hex_ids.rds") 

h3 <- tibble::tibble(h3_sh = h3_sh) %>% 
  mutate(h3_sh_split = strsplit(h3_sh, "-")) %>% 
  tidyr::unnest(h3_sh_split) 
```

**Comment by cole-brokamp** [comment]
I think I tried to get fancy and it backfired here -- this is definitely a bug.

Should we use your suggested approach above and then `left_join` that tibble in here instead of using the named lookup like I had?

https://github.com/degauss-org/h3/blob/09a1e2a8943c5f18c30c29a6e7cee2994870129a/entrypoint.R#L39

**Comment by erikarasnick** [comment]
I think that would work. I pulled this down to add a safe harbor geohash location to the tests, so I can just make this fix at the same time

**Comment by cole-brokamp** [comment]
awesome, a PR adding those tests and the fix would be great.
